# Generated by Django 5.2.10 on 2026-09-17 17:54

import core.models.policy
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceAccountLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_id", models.CharField(max_length=80)),
                ("event_count", models.PositiveIntegerField(default=0)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeviceIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("fingerprint", "Fingerprint")], max_length=20
                    ),
                ),
                ("external_id", models.CharField(max_length=100)),
                ("flags", models.JSONField(default=list)),
                (
                    "last_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "last_country",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("event_count", models.PositiveIntegerField(default=0)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="auditlog",
            name="label",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fraud", "Fraud"),
                    ("chargeback", "Chargeback"),
                    ("legit", "Legitimate"),
                    ("false_positive", "False positive"),
                ],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="labeled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="policy",
            name="device_thresholds",
            field=models.JSONField(
                blank=True, default=core.models.policy.get_device_thresholds_default
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["device_fingerprint", "timestamp"],
                name="core_auditl_device__11456e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["ip_address", "timestamp"],
                name="core_auditl_ip_addr_1259d0_idx",
            ),
        ),
        migrations.AddField(
            model_name="deviceaccountlink",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.application"
            ),
        ),
        migrations.AddConstraint(
            model_name="deviceidentity",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"),
                name="unique_device_identity_per_source",
            ),
        ),
        migrations.AddField(
            model_name="deviceaccountlink",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_links",
                to="core.deviceidentity",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.deviceidentity",
            ),
        ),
        migrations.AddIndex(
            model_name="deviceaccountlink",
            index=models.Index(
                fields=["device", "application", "last_seen_at"],
                name="core_device_device__c48994_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deviceaccountlink",
            index=models.Index(
                fields=["application", "client_id", "last_seen_at"],
                name="core_device_applica_9e7447_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="deviceaccountlink",
            constraint=models.UniqueConstraint(
                fields=("device", "application", "client_id"),
                name="unique_device_account_link",
            ),
        ),
    ]
