# Generated by Django 5.2.10 on 2026-09-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_device_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="collect_origins",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
