# Generated by Django 5.2.10 on 2026-09-18 18:02

import core.models.policy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_cases"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="mule_thresholds",
            field=models.JSONField(
                blank=True, default=core.models.policy.get_device_thresholds_default
            ),
        ),
    ]
